name: Action sample

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: execute echo command
        run: echo "Hello World!"
      - name: test
        run: |
          id
          ls -ld .
          docker-compose up -d test
          docker-compose run --rm test bash -c 'id; ls -ld .; mkdir subtest; echo $?'
